config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :notices

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'update', to: 'devise/registrations#edit', as: :update
    get 'logout', to: 'devise/sessions#destroy', as: :logout
    get 'recover', to: 'devise/passwords#new', as: :recover
  end

  root 'notices#index'

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  validates :title, :message, :user_id, presence: true
  validates :title, length: { maximum: 180 }

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true

  has_many :notices

  def full_name
  	first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :first_name, :last_name) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]
  before_action :is_permitted?, only: [:edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)
    @notice.user = current_user
    respond_to do |format|
      if @notice.save
        redirect_to @notice, notice: 'Notice was successfully created.'
      else
        render :new
      end
    end
  end

  # GET /notices/1/edit
  def edit
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_notice
    @notice = Notice.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notice_params
    params.require(:notice).permit(:title, :message, :user_id)
  end

  def is_permitted?
    redirect_to root_path unless (@notice.user_id == current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Noticeboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "OMÜ İlan Panosu", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li>
            <%= link_to "Çıkış Yap", logout_path %>
          </li>
        <% else %>
          <li>
            <%= link_to "Giriş Yap", login_path %>
          </li>
        <% end %>
      </ul>

    <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><%= current_user.full_name %></a></li>
      </ul>
    <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>

app/views/notices/_form.html.erb
<p>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p>İlan Ekle/Düzenle</p>
      </div>
      <div class="panel-body">
        <%= simple_form_for(@notice) do |f| %>
          <%= f.input :title, label: "Başlık", placeholder: 'Başlık 180 karakterden fazla olamaz!' %>
          <%= f.input :message, label: "İlan Metni" %>
          <%= f.button :submit, "Kaydet", class: 'btn btn-success' %>
          <%= link_to 'Geri Git', notices_path, class: 'btn btn-warning' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notices/edit.html.erb
<%= render 'form' %>

app/views/notices/index.html.erb
<div class="row">
  <div class="col-md-11">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p>Tüm İlanlar</p>
      </div>
      <div class="panel-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>İlan Başlığı</th>
              <th>İlan Metni</th>
              <th>İlanın Sahibi</th>
              <th>Oluşturulma</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @notices.each do |notice| %>
              <tr>
                <td><%= notice.title %></td>
                <td><%= truncate(notice.message, length: 180) %></td>
                <td><%= notice.user.full_name %></td>
                <td><%= time_ago_in_words(notice.created_at) %></td>
                <td><%= link_to 'Görüntüle', notice %></td>

                <% if user_signed_in? && (current_user == notice.user) %>
                  <td><%= link_to 'Düzenle', edit_notice_path(notice) %></td>
                  <td><%= link_to 'Sil', notice, method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>

                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <p class="pull-right">
      <%= link_to 'Yeni İlan Ekle', new_notice_path, class: "btn btn-info" %>
    </p>
  </div>
</div>

app/views/notices/new.html.erb
<%= render 'form' %>

app/views/notices/show.html.erb
<p>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p><%= @notice.title %></p>
      </div>
      <div class="panel-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>İlan Başlığı</th>
              <th>İlan Metni</th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <td><%= @notice.title %></td>
              <td><%= @notice.message %></td>
          </tr>
          </tbody>
        </table>
          <%= link_to 'Düzenle', edit_notice_path(@notice), class: "btn btn-warning" %> |
          <%= link_to 'Geri', notices_path, class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>